apiVersion: v1
kind: PersistentVolume
metadata:
  name: saltv-efs-vol
spec:
  accessModes:
  - ReadWriteMany
  capacity:
   storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: saltv-efs-pvc
    namespace: saltv-plex
  csi:
    driver: efs.csi.aws.com
    fsType: ext4
    volumeHandle: fs-046e13317fbd1a5be
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem
