apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: nightleak-deployment
    namespace: nightleak
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: nightleak
    serviceName: nightleak-svc
    template:
      metadata:
        labels:
          app: nightleak
      spec:
        containers:
        - args:
          - cd /var/www/ghost; sudo chown ghostadmin:ghostadmin /content; touch /content/logs;
            ghost start; tail -f /content/logs /dev/null;
          command:
          - /usr/bin/bash
          - -c
          image: 857893918939.dkr.ecr.us-east-1.amazonaws.com/nightleak:latest
          imagePullPolicy: Always
          name: nightleak
          ports:
          - containerPort: 2268
            protocol: TCP
          resources:
            requests:
              memory: "953Mi"
              cpu: "2000m"
            limits:
              memory: "1200Mi"
              cpu: "3000m"
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /content
            name: nightleak-efs-vol
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nightleak-efs-vol
          persistentVolumeClaim:
            claimName: nightleak-efs-pvc
kind: List

