apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saltv-efs-pvc
  namespace: saltv-plex
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: efs-sc
  volumeMode: Filesystem
  volumeName: saltv-efs-vol
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
