apiVersion: v1
kind: Service
metadata:
  name: saltv-svc
  namespace: saltv-plex
spec:
  type: NodePort
  ports:
  - nodePort: 32200
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app: saltv

