apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: saltv-deployment
    namespace: saltv-plex
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: saltv
    serviceName: saltv-svc
    template:
      metadata:
        labels:
          app: saltv
      spec:
        containers:
        - args:
          - cd /var/run/s6/services/plex && ./run;
          command:
          - /usr/bin/bash
          - -c
          image: 857893918939.dkr.ecr.us-east-1.amazonaws.com/saltv:latest
          imagePullPolicy: Always
          name: saltv
          ports:
          - containerPort: 32400
            protocol: TCP
          resources:
            requests:
              memory: "953Mi"
              cpu: "2000m"
            limits:
              memory: "1200Mi"
              cpu: "3000m"
          securityContext:
            allowPrivilegeEscalation: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /movies
            name: saltv-efs-vol
          env:
          - name: PUID 
            value: "1000"
          - name: PGID 
            value: "4000"
          - name: VERSION 
            value: "docker"
          - name: UMASK_SET 
            value: "022"
          - name: TZ
            value: "America/New_York"  
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: saltv-efs-vol
          persistentVolumeClaim:
            claimName: saltv-efs-pvc
kind: List

